<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Sekmen.StaticSiteGenerator</PackageId>
        <Product>Sekmen.StaticSiteGenerator</Product>
        <Title>Sekmen.StaticSiteGenerator</Title>
        <Authors>Hüseyin Sekmenoğlu</Authors>
        <PackageProjectUrl>https://github.com/sekmenhuseyin/Sekmen.StaticSiteGenerator</PackageProjectUrl>
        <RepositoryUrl>https://github.com/sekmenhuseyin/Sekmen.StaticSiteGenerator</RepositoryUrl>
        <Version>1.5.0</Version>
        <AssemblyVersion>1.5.0</AssemblyVersion>
        <FileVersion>1.5.0</FileVersion>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>logo.png</PackageIcon>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>D:\Proton\My files\About Company\Sekmen.Dev\sekmen.dev nuget package signature.snk</AssemblyOriginatorKeyFile>
        <PublicSign>true</PublicSign>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\logo.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>logo.png</Link>
        </None>
        <None Include="readme.md">
            <Pack>True</Pack>
            <PackagePath />
            <Link>readme.md</Link>
        </None>
    </ItemGroup>

</Project>
